services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rule-interface
    ports:
      - '3000:3000'
    env_file:
      - .env

  test:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: cypress
    # command: "tail -f /dev/null"
    ports:
      - '8801:8801'
    env_file:
      - .env
    volumes:
      - './packages/test/cypress/screenshots:/test/cypress/screenshots'
      - './packages/test/cypress/videos:/test/cypress/videos'
